.PHONY: install test vet fmt check

install:
	cd ata && go install ./...
	cd atx && go install ./...
	cd aor && go install ./...

test:
	cd ata && go test ./...
	cd atx && go test ./...

vet:
	cd ata && go vet ./...
	cd atx && go vet ./...
	cd aor && go vet ./...

fmt:
	gofmt -l .

check: vet test
